// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Data.TypeProviders")>]
[<assembly: AssemblyProductAttribute("FSharp.Data.TypeProviders")>]
[<assembly: AssemblyDescriptionAttribute("F# Type Providers using .NET Framework generators, was FSharp.Data.TypeProviders.dll")>]
[<assembly: AssemblyVersionAttribute("5.1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("5.1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Data.TypeProviders"
    let [<Literal>] AssemblyProduct = "FSharp.Data.TypeProviders"
    let [<Literal>] AssemblyDescription = "F# Type Providers using .NET Framework generators, was FSharp.Data.TypeProviders.dll"
    let [<Literal>] AssemblyVersion = "5.1.0.0"
    let [<Literal>] AssemblyFileVersion = "5.1.0.0"
