name: Build and Test PR

on:
  pull_request:
    branches:
    - main

jobs:
  build-windows:

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.200
    - name: Restore .NET local tools
      run: dotnet tool restore
    - name: Build and test (Release)
      run: dotnet test -c Release -v n
    - name: Build (Debug)
      run: dotnet build -c Debug -v n
